name: Feature request
description: Propose a product or engineering improvement.
title: '[Feature]: '
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are we solving?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints or context
