import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';

import { formatPaymentSuccessDate } from '@/services/payments-service';
import type { PaymentRecord } from '@/types/payments';

export type PaymentReceiptDownloadResult = {
  success: boolean;
  message: string;
};

function sanitizeFileNamePart(value: string) {
  return value.replace(/[^a-zA-Z0-9_-]/g, '-').replace(/-+/g, '-').toLowerCase();
}

function buildReceiptFileName(reference: string) {
  return `gcf-payment-receipt-${sanitizeFileNamePart(reference)}.pdf`;
}

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function buildPaymentReceiptHtml(payment: PaymentRecord) {
  const directionLabel = payment.direction === 'received' ? 'Received' : 'Sent';
  const counterpartLabel = payment.direction === 'received' ? 'Sender' : 'Recipient';
  const summary =
    payment.direction === 'received'
      ? `Received ${payment.displayAmount} from ${payment.recipientName}`
      : `Sent ${payment.displayAmount} to ${payment.recipientName}`;

  const summaryRows = [
    ['Summary', summary],
    ['Direction', directionLabel],
    ['Status', payment.statusLabel],
    ['Date / Time', formatPaymentSuccessDate(payment.createdAt)],
    ['Reference', payment.reference],
    ['Payment type', payment.typeLabel],
    [counterpartLabel, payment.recipientName],
    ['Destination', payment.destinationLabel],
    ['Bank', payment.recipientBankName],
    ['Amount', payment.displayAmount],
    ['Fee', payment.feeDisplay],
    ['Total payable', payment.totalPayableDisplay],
    ['Account', payment.sourceAccountLabel],
    ['Narration', payment.note || 'No note provided'],
  ] as [string, string][];

  return `<!doctype html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Greencard Payment Receipt</title>
    <style>
      body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
        color: #0f172a;
        margin: 0;
        padding: 28px;
        font-size: 12px;
      }
      .header {
        border-bottom: 1px solid #cbd5e1;
        margin-bottom: 18px;
        padding-bottom: 12px;
      }
      .brand {
        font-size: 18px;
        font-weight: 700;
        color: #0b3b63;
        margin: 0;
      }
      .title {
        margin: 6px 0 0;
        font-size: 14px;
        font-weight: 600;
      }
      .section-title {
        font-size: 12px;
        font-weight: 700;
        color: #0b3b63;
        margin: 16px 0 8px;
      }
      table {
        width: 100%;
        border-collapse: collapse;
      }
      td {
        border-bottom: 1px solid #e2e8f0;
        padding: 8px 0;
        vertical-align: top;
      }
      td.label {
        width: 36%;
        color: #475569;
        font-weight: 600;
      }
      td.value {
        color: #0f172a;
        font-weight: 500;
      }
      .footer {
        margin-top: 20px;
        color: #64748b;
        font-size: 11px;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <p class="brand">GCF</p>
      <p class="title">Payment receipt</p>
    </div>

    <div class="section-title">Transaction summary</div>
    <table>
      ${summaryRows
        .map(
          ([label, value]) =>
            `<tr><td class="label">${escapeHtml(label)}</td><td class="value">${escapeHtml(value)}</td></tr>`
        )
        .join('')}
    </table>

    <p class="footer">Generated by Greencard</p>
  </body>
</html>`;
}

async function saveReceiptOnDevice(
  html: string,
  fileName: string,
  reference: string
): Promise<PaymentReceiptDownloadResult> {
  const generated = await Print.printToFileAsync({ html });

  let targetUri = generated.uri;
  if (FileSystem.cacheDirectory) {
    const namedUri = `${FileSystem.cacheDirectory}${fileName}`;
    await FileSystem.deleteAsync(namedUri, { idempotent: true }).catch(() => undefined);
    await FileSystem.moveAsync({
      from: generated.uri,
      to: namedUri,
    }).catch(() => undefined);
    targetUri = namedUri;
  }

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(targetUri, {
      dialogTitle: `GCF receipt ${reference}`,
      mimeType: 'application/pdf',
      UTI: 'com.adobe.pdf',
    });
    return {
      success: true,
      message: 'PDF receipt is ready. Use the share sheet to save or export it.',
    };
  }

  return {
    success: true,
    message: 'PDF receipt generated successfully.',
  };
}

function waitForIframeLoad(iframe: HTMLIFrameElement) {
  return new Promise<void>((resolve, reject) => {
    const handleLoad = () => {
      iframe.removeEventListener('load', handleLoad);
      resolve();
    };

    const handleError = () => {
      iframe.removeEventListener('error', handleError);
      reject(new Error('Unable to load receipt preview.'));
    };

    iframe.addEventListener('load', handleLoad, { once: true });
    iframe.addEventListener('error', handleError, { once: true });
  });
}

async function printReceiptOnWeb(
  html: string,
  fileName: string
): Promise<PaymentReceiptDownloadResult> {
  const documentRef = globalThis.document;

  if (!documentRef) {
    throw new Error('Browser document is unavailable.');
  }

  const iframe = documentRef.createElement('iframe');
  iframe.setAttribute('title', fileName);
  iframe.style.position = 'fixed';
  iframe.style.right = '0';
  iframe.style.bottom = '0';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = '0';
  iframe.style.opacity = '0';
  iframe.style.pointerEvents = 'none';

  documentRef.body.appendChild(iframe);
  iframe.srcdoc = html;

  await waitForIframeLoad(iframe);

  const printWindow = iframe.contentWindow;

  if (!printWindow) {
    iframe.remove();
    throw new Error('Receipt preview is unavailable.');
  }

  const cleanup = () => {
    setTimeout(() => {
      iframe.remove();
    }, 300);
  };

  printWindow.addEventListener('afterprint', cleanup, { once: true });
  printWindow.focus();
  printWindow.print();

  return {
    success: true,
    message: 'Receipt summary opened. Choose Save as PDF in the print dialog to download it.',
  };
}

export async function downloadPaymentReceipt(
  payment: PaymentRecord
): Promise<PaymentReceiptDownloadResult> {
  if (payment.status !== 'completed') {
    return {
      success: false,
      message:
        payment.status === 'failed'
          ? 'This transaction failed. Contact support for help before downloading a receipt.'
          : 'Receipt is available only after this transaction is completed.',
    };
  }

  try {
    const fileName = buildReceiptFileName(payment.reference);
    const receiptHtml = buildPaymentReceiptHtml(payment);

    if (Platform.OS === 'web') {
      return await printReceiptOnWeb(receiptHtml, fileName);
    }

    return await saveReceiptOnDevice(receiptHtml, fileName, payment.reference);
  } catch {
    return {
      success: false,
      message: 'Unable to download receipt right now. Please try again.',
    };
  }
}
